"""
H-Automate — pdf_generator.py
PDF report generation using WeasyPrint.

Generates consultant-style business reports from diagnosis data.
"""

from weasyprint import HTML, CSS
from datetime import datetime
import os


def generate_business_report(
    diagnosis: str,
    metrics: dict,
    business_type: str,
    missing_fields: list = None,
    warnings: list = None
) -> bytes:
    """
    Generate a consultant-style PDF report from diagnosis data.
    
    Parameters:
        diagnosis: Full diagnosis text from Groq
        metrics: Structured metrics dict from data_cleaner
        business_type: Type of business analyzed
        missing_fields: List of fields that couldn't be calculated
        warnings: List of data quality warnings
    
    Returns:
        bytes: PDF file content
    """
    
    # Parse diagnosis sections
    sections = parse_diagnosis(diagnosis)
    
    # Build HTML content
    html_content = build_html_report(
        sections=sections,
        metrics=metrics,
        business_type=business_type,
        missing_fields=missing_fields or [],
        warnings=warnings or []
    )
    
    # Generate PDF
    pdf_bytes = HTML(string=html_content).write_pdf(
        stylesheets=[CSS(string=get_pdf_styles())]
    )
    
    return pdf_bytes


def parse_diagnosis(diagnosis: str) -> dict:
    """Parse diagnosis text into structured sections."""
    sections = {
        'health_snapshot': '',
        'diagnosis': '',
        'causes': '',
        'actions': '',
        'workflows': '',
        'note': ''
    }
    
    # Split by section markers
    parts = diagnosis.split('---')
    
    for part in parts:
        part = part.strip()
        
        if 'BUSINESS HEALTH SNAPSHOT' in part:
            sections['health_snapshot'] = part.replace('BUSINESS HEALTH SNAPSHOT', '').strip()
        elif 'AI DIAGNOSIS' in part:
            sections['diagnosis'] = part.replace('AI DIAGNOSIS', '').strip()
        elif 'LIKELY CONTRIBUTING FACTORS' in part:
            sections['causes'] = part.replace('LIKELY CONTRIBUTING FACTORS', '').strip()
        elif 'RECOMMENDED ACTIONS' in part:
            sections['actions'] = part.replace('RECOMMENDED ACTIONS', '').strip()
        elif 'SUGGESTED AUTOMATION WORKFLOWS' in part:
            sections['workflows'] = part.replace('SUGGESTED AUTOMATION WORKFLOWS', '').strip()
        elif 'IMPORTANT NOTE' in part:
            sections['note'] = part.replace('IMPORTANT NOTE', '').strip()
    
    return sections


def build_html_report(
    sections: dict,
    metrics: dict,
    business_type: str,
    missing_fields: list,
    warnings: list
) -> str:
    """Build HTML content for the PDF report."""
    
    date_str = datetime.now().strftime("%B %d, %Y")
    business_name = business_type.replace('-', ' ').title()
    
    # Build metrics HTML
    metrics_html = build_metrics_html(metrics)
    
    # Build warnings HTML
    warnings_html = ''
    if warnings:
        warnings_html = '<div class="warning-box">'
        warnings_html += '<h3>Data Quality Notes</h3><ul>'
        for warning in warnings:
            warnings_html += f'<li>{warning}</li>'
        warnings_html += '</ul></div>'
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>H-Automate Business Report</title>
    </head>
    <body>
        <div class="header">
            <h1>Business Analysis Report</h1>
            <div class="meta">
                <p><strong>Business Type:</strong> {business_name}</p>
                <p><strong>Report Date:</strong> {date_str}</p>
                <p><strong>Generated by:</strong> H-Automate AI</p>
            </div>
        </div>
        
        <div class="section">
            <h2>Executive Summary</h2>
            <p>This report provides an AI-powered analysis of your business operations based on sales transaction data. The insights below are designed to help you make informed decisions about inventory, pricing, customer retention, and operational efficiency.</p>
        </div>
        
        <div class="section">
            <h2>Business Health Snapshot</h2>
            <div class="health-snapshot">
                <pre>{sections['health_snapshot']}</pre>
            </div>
        </div>
        
        {metrics_html}
        
        <div class="section">
            <h2>AI Diagnosis</h2>
            <div class="diagnosis-text">
                {format_text_with_paragraphs(sections['diagnosis'])}
            </div>
        </div>
        
        <div class="section">
            <h2>Likely Contributing Factors</h2>
            <div class="causes-text">
                {format_text_with_paragraphs(sections['causes'])}
            </div>
        </div>
        
        <div class="section">
            <h2>Recommended Actions</h2>
            <div class="actions-text">
                {format_text_with_paragraphs(sections['actions'])}
            </div>
        </div>
        
        <div class="section">
            <h2>Suggested Automation Workflows</h2>
            <div class="workflows-text">
                {format_text_with_paragraphs(sections['workflows'])}
            </div>
        </div>
        
        {warnings_html}
        
        <div class="note-box">
            <p>{sections['note']}</p>
        </div>
        
        <div class="footer">
            <p>© 2026 H-Automate - AI Business Assistant for Nigerian SMEs</p>
            <p>This report is confidential and intended solely for the business owner.</p>
        </div>
    </body>
    </html>
    """
    
    return html


def build_metrics_html(metrics: dict) -> str:
    """Build HTML for key metrics section."""
    if not metrics:
        return ''
    
    html = '<div class="section"><h2>Key Metrics</h2><div class="metrics-grid">'
    
    # Total transactions
    if 'total_transactions' in metrics:
        m = metrics['total_transactions']
        html += f'''
        <div class="metric-card">
            <h4>Total Transactions</h4>
            <p class="metric-value">{m['value']:,}</p>
            <p class="metric-detail">{m.get('date_range', 'N/A')}</p>
        </div>
        '''
    
    # Revenue trend
    if 'revenue_trend' in metrics:
        m = metrics['revenue_trend']
        trend_class = 'trend-up' if 'growing' in m['value'] else 'trend-down' if 'declining' in m['value'] else 'trend-stable'
        html += f'''
        <div class="metric-card {trend_class}">
            <h4>Revenue Trend</h4>
            <p class="metric-value">{m['value'].title()}</p>
            <p class="metric-detail">{m.get('pct_change', 'N/A')}</p>
        </div>
        '''
    
    # Top products
    if 'top_products' in metrics:
        m = metrics['top_products']
        html += '<div class="metric-card full-width"><h4>Top Products by Revenue</h4><ul>'
        for product, share in list(m['value'].items())[:5]:
            html += f'<li><strong>{product}:</strong> {share}</li>'
        html += '</ul></div>'
    
    html += '</div></div>'
    return html


def format_text_with_paragraphs(text: str) -> str:
    """Format text with proper paragraph breaks."""
    if not text:
        return '<p>No data available.</p>'
    
    # Split by double newlines for paragraphs
    paragraphs = text.split('\n\n')
    html = ''
    
    for para in paragraphs:
        para = para.strip()
        if para:
            # Check if it's a list item
            if para.startswith(('1.', '2.', '3.', '4.', '5.', '-', '•')):
                html += f'<p class="list-item">{para}</p>'
            else:
                html += f'<p>{para}</p>'
    
    return html


def get_pdf_styles() -> str:
    """Return CSS styles for the PDF."""
    return """
    @page {
        size: A4;
        margin: 2cm;
    }
    
    body {
        font-family: 'Inter', 'Helvetica', 'Arial', sans-serif;
        color: #111827;
        line-height: 1.6;
        font-size: 11pt;
    }
    
    .header {
        border-bottom: 3px solid #1E40AF;
        padding-bottom: 20px;
        margin-bottom: 30px;
    }
    
    h1 {
        color: #1E40AF;
        font-size: 28pt;
        margin: 0 0 15px 0;
        font-weight: 700;
    }
    
    h2 {
        color: #14B8A6;
        font-size: 18pt;
        margin: 25px 0 15px 0;
        font-weight: 600;
        border-bottom: 2px solid #E5E7EB;
        padding-bottom: 8px;
    }
    
    h3 {
        color: #1E40AF;
        font-size: 14pt;
        margin: 15px 0 10px 0;
        font-weight: 600;
    }
    
    h4 {
        color: #374151;
        font-size: 12pt;
        margin: 10px 0 5px 0;
        font-weight: 600;
    }
    
    .meta {
        color: #6B7280;
        font-size: 10pt;
    }
    
    .meta p {
        margin: 5px 0;
    }
    
    .section {
        margin-bottom: 25px;
        page-break-inside: avoid;
    }
    
    .health-snapshot {
        background: #F8FAFC;
        padding: 15px;
        border-radius: 8px;
        border-left: 4px solid #1E40AF;
    }
    
    .health-snapshot pre {
        font-family: 'Courier New', monospace;
        font-size: 10pt;
        margin: 0;
        white-space: pre-wrap;
    }
    
    .metrics-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 15px;
        margin-top: 15px;
    }
    
    .metric-card {
        background: #F8FAFC;
        padding: 15px;
        border-radius: 8px;
        border: 1px solid #E5E7EB;
    }
    
    .metric-card.full-width {
        grid-column: 1 / -1;
    }
    
    .metric-card.trend-up {
        border-left: 4px solid #10B981;
    }
    
    .metric-card.trend-down {
        border-left: 4px solid #EF4444;
    }
    
    .metric-card.trend-stable {
        border-left: 4px solid #F59E0B;
    }
    
    .metric-value {
        font-size: 20pt;
        font-weight: 700;
        color: #1E40AF;
        margin: 5px 0;
    }
    
    .metric-detail {
        font-size: 9pt;
        color: #6B7280;
        margin: 0;
    }
    
    .metric-card ul {
        margin: 10px 0 0 0;
        padding-left: 20px;
    }
    
    .metric-card li {
        margin: 5px 0;
        font-size: 10pt;
    }
    
    .diagnosis-text p,
    .causes-text p,
    .actions-text p,
    .workflows-text p {
        margin: 10px 0;
        text-align: justify;
    }
    
    .list-item {
        margin-left: 20px;
        text-indent: -20px;
    }
    
    .warning-box {
        background: #FEF3C7;
        border: 1px solid #F59E0B;
        border-radius: 8px;
        padding: 15px;
        margin: 20px 0;
    }
    
    .warning-box h3 {
        color: #D97706;
        margin-top: 0;
    }
    
    .warning-box ul {
        margin: 10px 0 0 0;
        padding-left: 20px;
    }
    
    .warning-box li {
        margin: 5px 0;
        color: #92400E;
    }
    
    .note-box {
        background: #DBEAFE;
        border-left: 4px solid #1E40AF;
        padding: 15px;
        margin: 25px 0;
        font-size: 10pt;
        font-style: italic;
        color: #1E3A8A;
    }
    
    .note-box p {
        margin: 0;
    }
    
    .footer {
        margin-top: 40px;
        padding-top: 20px;
        border-top: 2px solid #E5E7EB;
        text-align: center;
        font-size: 9pt;
        color: #6B7280;
    }
    
    .footer p {
        margin: 5px 0;
    }
    """


# Test function
if __name__ == "__main__":
    test_diagnosis = """
---
BUSINESS HEALTH SNAPSHOT
Revenue Stability: 54/100 — Declining
Customer Activity: 61/100 — Moderate
Expense Efficiency: 78/100 — Healthy
Inventory Health: 48/100 — Needs Attention
Overall Business Health: 60/100 — Needs Attention
Top Risk: Revenue has declined 29% over the last 60 days with no recovery signal.

---
AI DIAGNOSIS
Analysis of 1,613 transactions across January–April 2026 reveals a business under moderate stress.

---
LIKELY CONTRIBUTING FACTORS
1. Seasonal demand shift
2. Dead stock accumulation
3. No repeat customer retention mechanism

---
RECOMMENDED ACTIONS
Immediate (This Week):
- Stop restocking Biscuits and Tissue Paper

Short-Term (Next 30 Days):
- Introduce a simple loyalty nudge

---
SUGGESTED AUTOMATION WORKFLOWS
1. Weekly Revenue Summary
2. Dead Stock Alert
3. Restock Reminder

---
IMPORTANT NOTE
These findings are based on sales transaction patterns only.
"""
    
    test_metrics = {
        'total_transactions': {'value': 1613, 'date_range': 'Jan 1 - Apr 30, 2026'},
        'revenue_trend': {'value': 'declining', 'pct_change': '-29.6%'},
        'top_products': {
            'value': {
                'Rice': '31.0%',
                'Vegetable Oil': '22.0%',
                'Indomie': '14.0%'
            }
        }
    }
    
    pdf_bytes = generate_business_report(
        diagnosis=test_diagnosis,
        metrics=test_metrics,
        business_type='mini-mart'
    )
    
    with open('test_report.pdf', 'wb') as f:
        f.write(pdf_bytes)
    
    print("Test PDF generated: test_report.pdf")

# Made with Bob
